// Mocks generated by Mockito 5.4.4 from annotations
// in WayFinder/test/integration_tests/R6_Itest.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:WayFinder/model/location.dart' as _i6;
import 'package:WayFinder/model/UserApp.dart' as _i4;
import 'package:WayFinder/viewModel/adapters/DBAdapterLocation.dart' as _i5;
import 'package:WayFinder/viewModel/adapters/DbAdapterUserApp.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DbAdapterUserApp].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbAdapterUserApp extends _i1.Mock implements _i2.DbAdapterUserApp {
  MockDbAdapterUserApp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserApp?> createUser(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<_i4.UserApp?>.value(),
      ) as _i3.Future<_i4.UserApp?>);

  @override
  _i3.Future<_i4.UserApp?> logInCredenciales(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logInCredenciales,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<_i4.UserApp?>.value(),
      ) as _i3.Future<_i4.UserApp?>);

  @override
  _i3.Future<bool> logOut() => (super.noSuchMethod(
        Invocation.method(
          #logOut,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [DbAdapterLocation].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbAdapterLocation extends _i1.Mock implements _i5.DbAdapterLocation {
  MockDbAdapterLocation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> createLocationFromCoord(_i6.Location? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocationFromCoord,
          [location],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> createLocationFromTopo(_i6.Location? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocationFromTopo,
          [location],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteLocation(_i6.Location? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocation,
          [location],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Set<_i6.Location>> getLocationList() => (super.noSuchMethod(
        Invocation.method(
          #getLocationList,
          [],
        ),
        returnValue: _i3.Future<Set<_i6.Location>>.value(<_i6.Location>{}),
      ) as _i3.Future<Set<_i6.Location>>);

  @override
  _i3.Future<bool> addFav(_i6.Location? location) => (super.noSuchMethod(
        Invocation.method(
          #addFav,
          [location],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> removeFav(_i6.Location? location) => (super.noSuchMethod(
        Invocation.method(
          #removeFav,
          [location],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}